resolved conflicts
usdot-fhwa-stol/autoware.ai pull request #109
Opened 2020-06-09 15:28 UTC by MishkaMN

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-06-10 13:20 UTC, msmcconnell requested changes
Some initial comments

2020-06-10 13:20 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +      if (it->second->id() == prim->id() && lanelet::IdVisitor().getId(it->first) == lanelet::IdVisitor().getId(new_element))
What is the condition being checked here? What does the IdVisitor do when you call getId()?

2020-06-10 13:20 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +void PrimitiveLayer<T>::update(Id element_id, const SubT& subelement)
So you removed the remove function. Does this update function still support that functionality? I don't see any calls to tree_ erase

2020-06-10 13:20 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +    throw NullptrError("Empty regulatory element passed to add()!");
Should this say update() instead of add()

2020-06-10 14:01 UTC, MishkaMN commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +      if (it->second->id() == prim->id() && lanelet::IdVisitor().getId(it->first) == lanelet::IdVisitor().getId(new_element))
it gets the id of the parameter. This condition is checking if the <regem,parameter> combination is there already in the unordered_map.

2020-06-10 14:02 UTC, MishkaMN commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +void PrimitiveLayer<T>::update(Id element_id, const SubT& subelement)
ah this is again refactoring error... thanks

2020-06-10 15:18 UTC, msmcconnell requested changes

2020-06-10 15:18 UTC, msmcconnell commented on common/map_file/include/map_file/map_param_loader.h
> +#include <std_msgs/String.h>
Why the extra include

2020-06-10 15:18 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +      if (it->second->id() == prim->id() && lanelet::IdVisitor().getId(it->first) == lanelet::IdVisitor().getId(new_element))
If this is an unordered map couldn't you just make a find call? That would be faster than iterating over the elements wouldn't it?

2020-06-10 15:18 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +void PrimitiveLayer<T>::update(Id element_id, const SubT& subelement)
Im pretty concerned by that. Shouldn't your old unit tests have failed if you removed that function?

2020-06-10 15:18 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +    regElem->setId(regulatoryElementLayer.uniqueId());
is uniqueId() only unique to the layer or the whole map? We need it to be unique to the whole map. I have done this in the past with lanelet::utilts::getId(), but if this is the same thing that is fine as well.

2020-06-10 15:18 UTC, msmcconnell commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +    utils::registerId(regElem->id());
We should probably check if the id is already in use and if it is then throw an exception. Unless this function already does that for us.

2020-06-10 15:36 UTC, MishkaMN commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +void PrimitiveLayer<T>::update(Id element_id, const SubT& subelement)
this is a template function, so I am only testing the specialized version of it with (lanelet_id, RegulatoryElementPre&) as I am only using that
Do you think I should write tests for these as well?

2020-06-11 17:32 UTC, MishkaMN commented on lanelet2/lanelet2_core/src/LaneletMap.cpp
> +    regElem->setId(regulatoryElementLayer.uniqueId());
I checked this and all the layer's uniqueId uses one global function utils::getId(). so it is unique in the map, but I changed it to be clear

2020-06-11 17:39 UTC, msmcconnell approved these changes

2020-06-11 20:17 UTC, merged