add gpu flag
usdot-fhwa-stol/autoware.ai pull request #135
Opened 2021-01-28 16:21 UTC by itabrl

# PR Details
## Description

adding gpu flag to build

## Related Issue

#894

## How Has This Been Tested?
deployed on white pacifica

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-28 16:55 UTC, aswath1 submitted a review, later dismissed

2021-01-28 17:56 UTC, msmcconnell requested changes

2021-01-28 17:56 UTC, msmcconnell commented on autoware/ros/carma_autoware_build
> +    AUTOWARE_COMPILE_WITH_CUDA=1 colcon build --cmake-args "${autoware_build_args}" --executor sequential --install-base ./ros/install --packages-up-to ${AUTOWARE_PACKAGE_SELECTION}
We need to make sure we have an approach for how to keep supporting our VMs. We can discuss on slack

2021-02-04 16:46 UTC, msmcconnell requested changes

2021-02-04 16:46 UTC, msmcconnell commented on core_perception/vision_darknet_detect/CMakeLists.txt
> +# if (USE_CUDA)
We should keep the CUDA guard I would think. That will keep it compatible if we removed the build with CUDA flag. I think the more robust solution here would be to replace the ELSE() with ENDIF() such that non-cuda is always built but with-cuda is only built when the flag is provided.

2021-02-05 14:58 UTC, msmcconnell approved these changes
We will wait to merge till all 3 PRs are ready

2021-02-05 16:08 UTC, merged