Signalized Intersection Manager support
usdot-fhwa-stol/autoware.ai pull request #187
Opened 2021-12-03 18:51 UTC by MishkaMN

# PR Details
## Description

TODO
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-06 14:50 UTC, msmcconnell commented
This PR could use more description

2021-12-06 14:54 UTC, msmcconnell requested changes
Looks good, but I believe this change also changes the XML description so please update that in the README accordingly.

2021-12-07 13:58 UTC, MishkaMN commented
> Looks good, but I believe this change also changes the XML description so please update that in the README accordingly.

Just updated the README.md and updated the PR description

2021-12-10 15:12 UTC, msmcconnell approved these changes

2021-12-10 15:13 UTC, merged