Feature/uc3 (return RED when predicting signal outside available interval)
usdot-fhwa-stol/autoware.ai pull request #232
Opened 2022-09-29 10:26 UTC by MishkaMN

# PR Details
## Description

Support dynamic SPAT when predicting signal states. If time_stamp requested is outside available dynamic spat time interval, return STOP_AND_WAIT

## Related Issue
Part of assorted fixes here. Supports this PR:
https://github.com/usdot-fhwa-stol/carma-platform/pull/1919

## Motivation and Context
TSMO UC3.

## How Has This Been Tested?
Integration tested on Black Pacifica with UC3 MAP/SPAT

## Types of changes

- [X] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [X] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-09-29 13:13 UTC, msmcconnell requested changes

2022-09-29 13:13 UTC, msmcconnell commented on common/lanelet2_extension/lib/CarmaTrafficSignal.cpp
> +    // if requested time is BEFORE recorded states' time interval, return STOP_AND_WAIT
typo STOP_AND_REMAIN

2022-09-29 13:13 UTC, msmcconnell commented on common/lanelet2_extension/lib/CarmaTrafficSignal.cpp
> +    // if requested time is AFTER recorded states' time interval, return STOP_AND_WAIT
Typo STOP_AND_REMAIN

2022-09-29 13:13 UTC, msmcconnell commented on common/lanelet2_extension/lib/CarmaTrafficSignal.cpp
> +      LOG_WARN_STREAM("CarmaTrafficSignal doesn't have enough state saved, so returning STOP_AND_WAIT state! End_time: " << end_infinity_time);
Typo STOP_AND_REMAIN

2022-09-29 13:13 UTC, msmcconnell commented on common/lanelet2_extension/lib/CarmaTrafficSignal.cpp
> +      return std::pair<boost::posix_time::ptime, CarmaTrafficSignalState>(end_infinity_time, CarmaTrafficSignalState::STOP_AND_REMAIN); //end at 03:14:07 on Tuesday, 19 January 2038.
Confusing comment //end at 03:14:07 on Tuesday, 19 January 2038.

2022-09-30 14:35 UTC, MishkaMN commented on common/lanelet2_extension/lib/CarmaTrafficSignal.cpp
> +      return std::pair<boost::posix_time::ptime, CarmaTrafficSignalState>(end_infinity_time, CarmaTrafficSignalState::STOP_AND_REMAIN); //end at 03:14:07 on Tuesday, 19 January 2038.
I moved the comment to next to the actual number

2022-09-30 18:12 UTC, msmcconnell approved these changes

2022-09-30 18:13 UTC, merged